title: "Eirin"
description: "Communication engineering, information theory, and math notes."

url: "https://eirinnnnnn.github.io"
baseurl: ""

# Theme
remote_theme: just-the-docs/just-the-docs

# Markdown engine
markdown: kramdown
kramdown:
  input: GFM

# GitHub Pages build helpers
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
